### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by sibiryakov** [scrapinghub/frontera#106]

**Comment by casertap** [comment]
Is there any plan to support python3 ? I could not find any clear indication that it is going that way.

**Comment by sibiryakov** [comment]
Yes, there's ongoning work, it's going to be finished till the end of august

**Comment by casertap** [comment]
Great news! you should make it clear somewhere. I guess now it is here.
Awesome work guys. Thanks.

**Comment by sibiryakov** [comment]
Solved in Frontera 0.6.0
