### ISSUE TITLE
remove optional dependencies from install_requires

### ISSUE THREAD

**Issue by kmike** [scrapinghub/frontera#2]
I'm not 100% sure about that, but it seems some of the requirements in setup.py are optional. For example, based on docs it seems Crawl Frontier can be used without SQLAlchemy or without pydot. But now it can't because these requirements are in `install_requires`. I think it is better for `install_requires` to be minimal - what do you think about removing most of packages from it?

Versioning in `install_requires` also looks too restrictive - are latest versions really required? Pinning versions with `==` is problematic because if a new combatible version of a package is released it won't be possible to use it with an existing crawl-frontier version.

IMHO `install_requires` should exclude versions that are known not to work, not versions about which we're unsure. We may create requirements.txt file with pinned package versions which are known to work.

**Comment by sibiryakov** [comment]
@kmike It has been a long time ) Mikhail, if you think it's ok if someone will try to use a backend which has no installed dependency after ``pip install frontera`` and getting ambiguous message? What's the common practice for this?

**Comment by kmike** [comment]
I think getting ImportError is fine; I don't see it as ambiguous because the exception message says what package fails to be imported.

As @gatufo said, we can document dependencies and provide them in `extras_require`, so people can run e.g.

```
pip install frontera[sql-backend]
```
and get frontera with all dependencies necessary for SQL based backend.
