### ISSUE TITLE
Recorder Error

### ISSUE THREAD

**Issue by dersteppenwolf** [scrapinghub/frontera#201]
There was a problem trying to record a crawl:

> /python2.7/site-packages/frontera/contrib/scrapy/schedulers/recording.py", line 8, in <module>
>     from frontera import graphs
> ImportError: cannot import name graphs

version_version = '0.6.0'

**Comment by sibiryakov** [comment]
Is this problem still exists @dersteppenwolf ? Sorry for not responding in time.
