### ISSUE TITLE
How to set cookies at very beginning of crawling

### ISSUE THREAD

**Issue by Bundas** [scrapinghub/frontera#207]
I am having hard times figuring out how to set cookies in examples/general-spider

I am not sure but I think that the first request is not made by general spider.py but by something else. So my question is **How to send cookie in very beginning of crawling**. How to send cookie in very first request, respectively. 

This is how I use cookies in spider.

```
from scrapy.spider import Spider
from scrapy.http import Request
from scrapy.http.response.html import HtmlResponse
from scrapy.linkextractors import LinkExtractor
import requests
import json

class GeneralSpider(Spider):
    name = 'general'

    def __init__(self, *args, **kwargs):
        super(GeneralSpider, self).__init__(*args, **kwargs)
        self.le = LinkExtractor()

    def parse(self, response):
        if not isinstance(response, HtmlResponse):
            return

        for link in self.le.extract_links(response):
            r = Request(url=link.url, cookies={'isAnAdult':'true'}) ####  <- HEEEERE
            r.meta.update(link_text=link.text)
            yield r
```

But this code doesn't send the cookie in first request.

**Comment by Preetwinder** [comment]
In case of the general spider the seeds text file is used as the start_urls list. So if you want to send a cookie for these URLs, one solution would be to override the `make_requests_from_url` method for your spider with something like - 
```
def make_requests_from_url(self, url):
    return Request(url, cookies={'isAnAdult':'true'})
```

**Comment by sibiryakov** [comment]
Hey @Bundas is it solved? Can I close the issue?

**Comment by Bundas** [comment]
@sibiryakov yep, it works

**Comment by liho00** [comment]
> In case of the general spider the seeds text file is used as the start_urls list. So if you want to send a cookie for these URLs, one solution would be to override the `make_requests_from_url` method for your spider with something like -
> 
> ```
> def make_requests_from_url(self, url):
>     return Request(url, cookies={'isAnAdult':'true'})
> ```
Spider.make_requests_from_url is deprecated , how to set header at very beginning in frontera?
https://github.com/scrapy/scrapy/pull/1728

**Comment by sibiryakov** [comment]
request.headers
