### ISSUE TITLE
Writing custom crawling strategy tutorial

### ISSUE THREAD

**Issue by sibiryakov** [scrapinghub/frontera#222]
short plan:
- motivation: what & when to crawl
- the tutorial problem have to include: 
  - revisiting,
  - state management (one-time visit, combination with revisiting),
  - creation of request with state lookup in state storage,
  - using meta to store per-request information through the whole pipeline.

**Comment by ArlasJ** [comment]
Hi. Is there a tutorial already? We got a semester project for a crawler in university. We wanted to write a custom strategy.

**Comment by sibiryakov** [comment]
No, it's ready. But you could look into existing crawling strategies:
https://github.com/scrapinghub/frontera/blob/master/examples/cluster/bc/broadcrawl/__init__.py#L48
and crawling strategy base class
https://github.com/scrapinghub/frontera/blob/master/frontera/worker/strategies/__init__.py#L11

**Comment by liho00** [comment]
@sibiryakov Hi there, the link doesn't exist already, Is there any tutorial provided except from the official documentation?

**Comment by liho00** [comment]
@sibiryakovThis link does not work. If possible, can you provide it again?

**Comment by sibiryakov** [comment]
Hi, have a look at this https://frontera.readthedocs.io/en/latest/topics/custom_crawling_strategy.html
