### ISSUE TITLE
simplify examples of Scrapy settings

### ISSUE THREAD

**Issue by kmike** [scrapinghub/frontera#242]
In frontera docs and examples Scrapy middlewares are added like this:

```py
from scrapy.settings.default_settings import SPIDER_MIDDLEWARES, DOWNLOADER_MIDDLEWARES

SPIDER_MIDDLEWARES.update({
    'frontera.contrib.scrapy.middlewares.schedulers.SchedulerSpiderMiddleware': 999,
    'frontera.contrib.scrapy.middlewares.seeds.file.FileSeedLoader': 1,
})
DOWNLOADER_MIDDLEWARES.update({
    'frontera.contrib.scrapy.middlewares.schedulers.SchedulerDownloaderMiddleware': 999,
})
```

Is this a requirement? Usually users should just define their settings like this, without any imports:

```py
SPIDER_MIDDLEWARES = {
    'frontera.contrib.scrapy.middlewares.schedulers.SchedulerSpiderMiddleware': 999,
    'frontera.contrib.scrapy.middlewares.seeds.file.FileSeedLoader': 1,
}
DOWNLOADER_MIDDLEWARES = {
    'frontera.contrib.scrapy.middlewares.schedulers.SchedulerDownloaderMiddleware': 999,
}
```

Changing objects from `scrapy.settings.default_settings` directly is not supported by Scrapy, there are no docs/tests for this, and it may break in subtle ways. Scrapy settings are not global, but here a global variable is changed (the one which is used as an initial value of settings).

For example, if there are  two settings files, you set SCRAPY_SETTINGS_MODULE=settings1.py env variable to use `settings1.py` as settings, then run `scrapy crawl foo`. It tries to find a spider `foo` - to do so it imports python files, `settings2.py` get imported, global `scrapy.settings.default_settings.DOWNLOADER_MIDDLEWARES` is patched ==> you get options from `settings2.py` applied, not only from `settings1.py`.

**Comment by sibiryakov** [comment]
Sure, absolutely makes sense. Could you make a PR?

**Comment by kmike** [comment]
@sibiryakov yep!
