### ISSUE TITLE
Does Frontera do anything about spider traps?

### ISSUE THREAD

**Issue by olalonde** [scrapinghub/frontera#248]
I'm looking to do broad crawling using frontera but couldn't find anything in the docs regarding [spider trap](https://en.wikipedia.org/wiki/Spider_trap) detection (e.g. not crawling a calendar website ad infinitum). 

The best I could find regarding that was a hard coded 10K page limit per host in the `examples/cluster/bc` example which seems sort of arbitrary and limiting. 

Does Frontera not have any smart strategy to detect spider traps? Or am I wrong to think this is an issue?

My worry with a hard coded limit is that a website like Wikipedia has well over 10K interesting pages to crawl but at the same time, I don't want my spider to be stuck on some useless calendar website that dynamically generates new URLs.

**Comment by sibiryakov** [comment]
Hi @olalonde Frontera has no algorithms to avoid that, but there is a way to implement your own custom crawling strategy, which is class loaded by strategy worker. Here is the parent class interface
http://frontera.readthedocs.io/en/latest/topics/own_crawling_strategy.html

What you have found is just an example crawling strategy and it implies that users will customize it according to their needs.

**Comment by olalonde** [comment]
Thanks @sibiryakov. Is there an existing crawling strategy that would be well suited for broad crawling? My goal is to crawl as many pages from the web as possible.

**Comment by sibiryakov** [comment]
That one should crawl deep, until there will be no unvisited links
https://github.com/scrapinghub/frontera/blob/master/frontera/worker/strategies/bfs.py
