### ISSUE TITLE
OPIC backend?

### ISSUE THREAD

**Issue by trungtv** [scrapinghub/frontera#249]
Is there any OPIC backend in the latest frontera? The document for the old version is here 
[http://crawl-frontier.readthedocs.io/en/opic/topics/opic-backend.html](url)

**Comment by sibiryakov** [comment]
No, it's not there @trungtv and we (at SH) don't plan to work in this direction.

**Comment by trungtv** [comment]
Thanks @sibiryakov

**Comment by sibiryakov** [comment]
I forgot to tell you there is https://github.com/scrapinghub/aduana, but it's not integrated with Frontera at the moment, and it's relatively hard to do so. However, I expect OPIC concept is implemented there.
