### ISSUE TITLE
Rename project to "Frontera"

### ISSUE THREAD

**Issue by pablohoffman** [scrapinghub/frontera#26]
Sine the beginning of the Crawl Frontier project, we knew we wanted to give a it a real name, something less generic than "crawl frontier", something that can be easy to identify and sounds well. There is a reason why Scrapy was called Scrapy and not "Web Crawler" :).

We have decided today on calling it "Frontera". I have reserved [the pypi name](https://pypi.python.org/pypi/frontera).

@plafl @sibiryakov can you do the rename?

**Comment by sibiryakov** [comment]
@pablohoffman sure! Give us some time, that requires walkthrough over the whole code base and documentation.

**Comment by pablohoffman** [comment]
@sibiryakov :+1:

**Comment by sibiryakov** [comment]
Anything else is needed?
