### ISSUE TITLE
Python 3.7 support

### ISSUE THREAD

**Issue by gastlich** [scrapinghub/frontera#336]
Python 3.7 introduced new reserved keywords *async* and *await*, which makes frontera unusable on the newest python, because of module called async located under following path:

https://github.com/scrapinghub/frontera/blob/master/frontera/utils/async.py

**Comment by sibiryakov** [comment]
Thank you @gastlich it should be easy to solve

**Comment by sibiryakov** [comment]
It should be fixed in latest (v0.8) release. Could you check @gastlich ?

**Comment by suzil** [comment]
I can confirm this is no longer an issue at least with Travis tests #379
