### ISSUE TITLE
ModuleNotFoundError: No module named 'frontier.workersetting

### ISSUE THREAD

**Issue by songproducer** [scrapinghub/frontera#340]
Hi,

I'm following this:
https://frontera.readthedocs.io/en/latest/topics/quick-start-distributed.html

But when I do:
python -m frontera.worker.db --config frontier.workersettings

I get:
ModuleNotFoundError: No module named 'frontier.workersetting

**Comment by nmweizi** [comment]
cd /examples/general-spider/

**Comment by sibiryakov** [comment]
Hi guys, both general-spider and quick-start-distributed are outdated, give us some time to update them.

**Comment by sibiryakov** [comment]
its fixed in latest release 0.8.0.1
