### ISSUE TITLE
Is the project still in progress？

### ISSUE THREAD

**Issue by kingkap** [scrapinghub/frontera#369]
Hi，I saw that the function of this project has been perfected. But I still have some doubts, is this project still being maintained? Is its follow-up function still under development?I just waiting for your reply. many thanks xx

**Comment by grammy-jiang** [comment]
Hi, @kingkap 

I think so. Scrapy and Frontera is the product of Scrapinghub.

Frontera is not as popular as Scrapy, but it is still open source - you can fork and fix any bugs, or add new features by yourself.

**Comment by sibiryakov** [comment]
Hi @kingkap, we don't have resources to add anything new, but we consider Frontera production-ready. So basically now we're doing mostly support, which is fixing critical bugs and trying to keep master green.
