### ISSUE TITLE
Does Apache Kafka need Apache Zookeeper to run Frontera?

### ISSUE THREAD

**Issue by liho00** [scrapinghub/frontera#370]
Because I want to install apache kafka, I realize that it depends on apache zookeeper. However, it is not specified in the documentation. Does Apache Kafka need Apache Zookeeper to run Frontera?

if possible would you like to share me how to install apache kafka in Ubuntu 18.04, as i just migrate  from Windows to Ubuntu just for using frontera. Hence, im very new to linux.

In addition, I would like to ask what standard modules or files need to be created to run frontera with apache kafka and apache hbase. In fact, I already know which files and modules should be configured in the Document Cluster Setup Guide, but I want to know the naming and arrangement of it with scrapy.

As far as I know, scrapy can use the scrapy startproject tutorial command to automatically generate the standard files and modules needed for scrapy.

Thanks in advance!

**Comment by sibiryakov** [comment]
Hi, ZK is mandatory requirement for Kafka, and Frontera is not using it directly. The easiest way to setup Kafka is to use Docker image or binary bundle from Confluent. Scrapy requires Frontera to be installed, and its using middleware and scheduler implementations from Fronteta.

**Comment by liho00** [comment]
@sibiryakov thanks your suggestion, but i have done installed kafka package in my pc. I have start my db worker module by this command `$ python -m frontera.worker.db --config tutorial.frontera.dbw --no-incoming --partitions 0 1` i got the result in below screenshots.

![Screenshot from 2019-06-06 15-43-10](https://user-images.githubusercontent.com/34411102/59015825-76113800-8872-11e9-8dbe-afcb348d41a2.png)
![Screenshot from 2019-06-06 15-43-21](https://user-images.githubusercontent.com/34411102/59015828-79a4bf00-8872-11e9-8d66-cb91cde1f2db.png)

It is an indefinite loop, is that normal? Sorry for this simple question, as im very new beginner in hbase, kafka and frontera.

**Comment by liho00** [comment]
@sibiryakov  Hi, thanks your suggestion about the kafka. But i have installed it in my pc. I tend to build kafka+hbase crawler.

I have few questions, first when i run this command 
`scrapy crawl tutorial -L INFO -s SPIDER_PARTITION_ID=0` 
i got this error 
`ModuleNotFoundError: No module named 'frontera.contrib.scrapy.middlewares.seeds'`
![Screenshot from 2019-06-06 23-37-04](https://user-images.githubusercontent.com/34411102/59047162-edb48680-88b5-11e9-88ad-e4d6b9e4eac4.png)


after i removed, i can run the scrapy, but 0 page crawled
`SPIDER_MIDDLEWARES = {
    'frontera.contrib.scrapy.middlewares.schedulers.SchedulerSpiderMiddleware': 999,
̶ ̶ ̶ ̶'̶f̶r̶o̶n̶t̶e̶r̶a̶.̶c̶o̶n̶t̶r̶i̶b̶.̶s̶c̶r̶a̶p̶y̶.̶m̶i̶d̶d̶l̶e̶w̶a̶r̶e̶s̶.̶s̶e̶e̶d̶s̶.̶f̶i̶l̶e̶.̶F̶i̶l̶e̶S̶e̶e̶d̶L̶o̶a̶d̶e̶r̶'̶:̶ ̶1̶,̶
}`
![Screenshot from 2019-06-06 23-52-23](https://user-images.githubusercontent.com/34411102/59047275-281e2380-88b6-11e9-9f0e-ff3832b7e654.png)

besides, my kafka didnt consume any message
![Screenshot from 2019-06-06 23-53-04](https://user-images.githubusercontent.com/34411102/59047361-4ab03c80-88b6-11e9-9b17-d261357cf965.png)

All my config is followed the document cluster setup guide. 
Thanks in advance!
