### ISSUE TITLE
HBaseQueue losing urls when using BC_MAX_REQUESTS_PER_HOST

### ISSUE THREAD

**Issue by a-shkarupin** [scrapinghub/frontera#393]
Hi,
[BC_MAX_REQUESTS_PER_HOST](https://frontera.readthedocs.io/en/latest/topics/frontera-settings.html#bc-max-requests-per-host)  description states:

> Don’t include (if possible) batches of requests containing requests for specific host if there are already more then specified count of maximum requests per host. This is a suggestion for broad crawling queue get algorithm.

However in practice, the urls exceeding specified count of maximum requests per host are dropped for a given row key. I would expect such urls to be included in later batches, not dropped.
This is the part of the code in question:
https://github.com/scrapinghub/frontera/blob/master/frontera/contrib/backends/hbase/__init__.py#L249

Is this expected behavior?

In case it is, this should be explicitly stated in the documentation to avoid possible misuse of the option.

Best regards

**Comment by sibiryakov** [comment]
Hi, these requests are skipped for batch of results prepared for _specific iteration_. They will stay in HBase table for subsequent runs. Only requests added to `trash_can` are removed completely.
