### ISSUE TITLE
pre-requisite for running examples?

### ISSUE THREAD

**Issue by vincentlaucy** [scrapinghub/frontera#42]
I tried to setup frontier with scrapy crawlSpider but no luck.

Then I clone the project and run the example with `scrapy crawl example`, still seems it finish with  requests being generated but no response being parsed.

am I missing anything or it is a version problem?  using scrapy 0.24.4  and frontera (0.3.0.post0.dev2)
```
2015-05-20 00:48:52+0800 [example] INFO: Dumping Scrapy stats:
	{'finish_reason': 'finished',
	 'finish_time': datetime.datetime(2015, 5, 19, 16, 48, 52, 562936),
	 'frontera/iterations': 0,
	 'frontera/pending_requests_count': 0,
	 'frontera/seeds_count': 4,
	 'log_count/DEBUG': 2,
	 'log_count/INFO': 9,
	 'start_time': datetime.datetime(2015, 5, 19, 16, 48, 52, 558849)}

```

**Comment by vincentlaucy** [comment]
seems it work after I downgrade to frontera v0.2.0

**Comment by sibiryakov** [comment]
This is related to this https://github.com/scrapinghub/frontera/pull/35 I'm going to release few bug fixes in a few days.

**Comment by sibiryakov** [comment]
Also, be aware of https://github.com/scrapinghub/frontera/issues/30

**Comment by sibiryakov** [comment]
@vincentlaucy What's the current situation? Is it working now? Closing this?

**Comment by vincentlaucy** [comment]
I tried w/ https://github.com/scrapinghub/frontera/tree/v0.3.3 and it seems working now - Thanks
