### ISSUE TITLE
Scrapy- Enabling Frontera middlewares removes the referer header from response objects

### ISSUE THREAD

**Issue by stejesh** [scrapinghub/frontera#58]
When i enable the following frontera middleware in scrapy

I lose all my referer headers in all my `response` objects

Is there anyway i can preserve the referrer?

The referer is available when i remove the following lines, but i need to enable these frontera middlewares

```
SPIDER_MIDDLEWARES.update({
    'frontera.contrib.scrapy.middlewares.schedulers.SchedulerSpiderMiddleware': 1000,
})


DOWNLOADER_MIDDLEWARES.update({
    'frontera.contrib.scrapy.middlewares.schedulers.SchedulerDownloaderMiddleware': 1000,
})

SCHEDULER = 'frontera.contrib.scrapy.schedulers.frontier.FronteraScheduler'
```

Also, the `referermiddleware` is enabled, i can see it when in the info/debug log when scrapy starts

**Comment by sibiryakov** [comment]
Hey @stejesh, thanks for the report! I need some additional information. Please tell more about how do you check for referer header presence? 

At the moment headers aren't preserved when requests are serializing to DB and deserializing back. It actually can be easily fixed.

**Comment by stejesh** [comment]
Hi @sibiryakov 

I check it inside my parse_data callback in scrapy this way

```
def parse_data(self, response)
    referer_url = response.request.headers.get('Referer', None)
    .... 
```

**Comment by stejesh** [comment]
Hi @sibiryakov do you have any suggestions to the above?

**Comment by sibiryakov** [comment]
@stejesh let me check!

**Comment by RajatGoyal** [comment]
@stejesh @sibiryakov using changes from this branch https://github.com/scrapinghub/frontera/pull/60, should make it work.

**Comment by sibiryakov** [comment]
@RajatGoyal you're right probably. Requests deserialized from Frontera are missing headers, and referrer middleware is using headers to storing referrer information.
@stejesh please wait until we merge Rajat's PR. You could try using Frontera from his branch and confirm that referrers are available, that will help us.

**Comment by stejesh** [comment]
@sibiryakov Thank you, will try and let you know

**Comment by stejesh** [comment]
hi @sibiryakov Thanks @RajatGoyal 

The headers are preserved now when using @RajatGoyal #60 branch

**Comment by sibiryakov** [comment]
@stejesh great! Now we have to work harder to merge it.

**Comment by sibiryakov** [comment]
@stejesh it was merged, and available in latest release.
