### ISSUE TITLE
403 not treated as error

### ISSUE THREAD

**Issue by RajatGoyal** [scrapinghub/frontera#61]
According to the HTTP standard, successful responses are those whose status codes are in the 200-300 range. But sqlalchemy backend is not treating 403 as a error and not populating error column. Essentially `request_error` function is not getting called.

**Comment by sibiryakov** [comment]
what about any other 4xx or 5xx?

**Comment by RajatGoyal** [comment]
Same. No error is logged based on response code.

**Comment by sibiryakov** [comment]
I think that's right behavior. Status code is written in database, and further operations is expected to be customized by user.
