### ISSUE TITLE
Confused about MAX_NEXT_REQUESTS

### ISSUE THREAD

**Issue by lljrsr** [scrapinghub/frontera#90]
Under [Production Crawling](https://github.com/scrapinghub/frontera/blob/5dd126294cd4c21c77500fc618d603c65e229fa0/docs/source/topics/production-broad-crawling.rst) an example is presented with N spiders and N SWs. The spider has twice the amount of `MAX_NEXT_REQUESTS` than the workers. And there is a comment that both values should be "consistent".
Under [Frontera Settings](https://github.com/scrapinghub/frontera/blob/5dd126294cd4c21c77500fc618d603c65e229fa0/docs/source/topics/frontera-settings.rst#max_next_requests) there is no mentioning about which ratio to use for SW and spider requests or what "consistent" means.
Then in the general-spider project the [spider](https://github.com/scrapinghub/frontera/blob/5dd126294cd4c21c77500fc618d603c65e229fa0/examples/general-spider/frontier/spider_settings.py#L4) has half of the `MAX_NEXT_REQUESTS` that the [workers](https://github.com/scrapinghub/frontera/blob/5dd126294cd4c21c77500fc618d603c65e229fa0/examples/general-spider/frontier/workersettings.py#L4) have.
Now I am a bit confused. Should `MAX_NEXT_REQUESTS` be the same for SWs and spiders or should a certain ratio be used?

**Comment by sibiryakov** [comment]
There is no recommendation possible that fits all use cases. It all depends on spiders request processing rates. Ideal case is when your transport layer holds 0 documents, meaning that all requests produced for fetching by DB worker is instantly consumed by spiders and processed. At the same time spider consumption rate is depending on many factors: internet connection latency, amount of spider parsing/scraping work, delays and auto throttling settings, usage of proxies, etc. 

So "consistent" means the user has to always think about both of them, these values are connected.

If this answers your question, any ideas how we can include this in docs?

**Comment by lljrsr** [comment]
I would write that down [here](https://github.com/scrapinghub/frontera/blob/5dd126294cd4c21c77500fc618d603c65e229fa0/docs/source/topics/frontera-settings.rst#max_next_requests).
Something like: 

The maximum number of requests returned by :attr:`get_next_requests <frontera.core.manager.FrontierManager.get_next_requests>` API method. This equals to the maximum amount of requests that each worker is pushing  to each batch and the requests each spider is consuming. Your chosen values should prohibit the zeromq queue from being empty and completely full during your crawl. This depends on many factors. E.g.  connection latency, amount of spider parsing/scraping work, delays, auto throttling settings, usage of proxies, etc. If the value is 0 (default), no maximum value will be used.

**Comment by sibiryakov** [comment]
It can be used without zeromq. May be it would be better to write a paragraph about such tuning somewhere else?

**Comment by lljrsr** [comment]
Oh sry that's right. You could just leave out the zeromq.
Yes, you could also put it into another section e.g. "FAQ" or "Troubleshooting".
