### ISSUE TITLE
Thrift compact protocoll should also be framed.

### ISSUE THREAD

**Issue by lljrsr** [scrapinghub/frontera#96]
In [the docs](http://frontera.readthedocs.org/en/latest/topics/frontera-settings.html#hbase-use-compact-protocol) you do not mention that one should also use the framed protocol.

**Comment by sibiryakov** [comment]
That's not our choice ;) I mean Frontera nothing can do with nuances of setting compact protocol on server side.

**Comment by lljrsr** [comment]
[Here](https://github.com/scrapinghub/frontera/blob/master/frontera/contrib/backends/hbase.py#L390) the framed protocol is explicitly set. In the docs there is no mentioning of it (only the compact protocol is being mentioned), neither is there an error message when only using the compact protocol.

**Comment by sibiryakov** [comment]
Yeah, you're right. Can you make a PR?
