### ISSUE TITLE
ZMQ_HOSTNAME cannot be a host name when connecting to broker

### ISSUE THREAD

**Issue by lljrsr** [scrapinghub/frontera#99]
When using a host name to connect via ZMQ an error is thrown because the socket tries to connect to the host name, but needs an IP address instead.

**Comment by sibiryakov** [comment]
What error? Can you post a stack trace and error message? According to docs it should be fine http://api.zeromq.org/4-0:zmq-tcp#toc4

**Comment by lljrsr** [comment]
With `elastic` assigned to my own IP in /etc/hosts:
```
python -m frontera.contrib.messagebus.zeromq.broker --hostname elastic
```
..throws:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/jrisr/Crawl/debug/frontera/frontera/contrib/messagebus/zeromq/broker.py", line 160, in <module>
    main()
  File "/home/jrisr/Crawl/debug/frontera/frontera/contrib/messagebus/zeromq/broker.py", line 155, in main
    server = Server(hostname, port)
  File "/home/jrisr/Crawl/debug/frontera/frontera/contrib/messagebus/zeromq/broker.py", line 51, in __init__
    spiders_in_s.bind(socket_config.spiders_in())
  File "zmq/backend/cython/socket.pyx", line 487, in zmq.backend.cython.socket.Socket.bind (zmq/backend/cython/socket.c:5156)
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:7535)
zmq.error.ZMQError: No such device
```
But
```
python -m frontera.contrib.messagebus.zeromq.broker --hostname wlp2s0
```
..and
```
python -m frontera.contrib.messagebus.zeromq.broker --hostname 192.168.1.50
```
is working.

**Comment by sibiryakov** [comment]
Here is the right link for the broker http://api.zeromq.org/4-0:zmq-tcp#toc3, because it binds to the socket. So, you're right either ip address or interface name. I hope you will find a time, to fix this :+1:

**Comment by lljrsr** [comment]
Is that sufficient?

**Comment by lljrsr** [comment]
Any update on this? I will stop working on Friday, it would be nice to merge this before that :) .

**Comment by sibiryakov** [comment]
You're leaving, or having vacation?

**Comment by lljrsr** [comment]
I am leaving.
:) why are you asking?

**Comment by sibiryakov** [comment]
just wondering, if I should expect any more contributions from you?

**Comment by lljrsr** [comment]
Not really. Maybe some of my colleagues will contribute something, but they will probably not contribute as much.

**Comment by sibiryakov** [comment]
Good luck then!
Can I add you to the authors? https://github.com/scrapinghub/frontera/pull/111/files

**Comment by lljrsr** [comment]
Of course. It is an honor to be added :) .

**Comment by lljrsr** [comment]
I double checked if everything works. Right now IP6 does not work on my machine. Therefore I cannot test it properly (only ip6-localhost works).
Other than that everything should work fine.
